/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 143
#define YY_END_OF_BUFFER 144
static yyconst short int yy_accept[397] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  144,  127,  123,   59,  124,   92,  121,  127,
       78,   79,  122,   49,   50,   76,   74,   64,   75,   93,
       77,  117,  115,   63,   62,   72,   67,   70,  127,   60,
       61,   81,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,   57,   80,   58,   82,  130,  128,  130,  132,  131,
      141,  135,  133,  134,  141,  141,  142,  143,  112,  105,
      104,  112,  112,  112,  112,   59,   69,  113,   89,   65,
       87,   90,   83,   91,   84,    0,  125,  126,   88,    0,

        0,    0,  115,   94,   95,   73,   68,   71,    0,    0,
      114,  114,   96,  114,  114,  114,  114,  114,  114,  114,
        9,  114,  114,  114,  114,  114,  114,  114,  114,    1,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  114,
      114,   66,  129,  136,  139,  137,  138,  140,  104,    0,
        0,    0,    0,  113,   51,  120,  116,   85,   86,  114,
      114,  114,  114,  114,  114,  114,  114,  114,  114,  100,
      114,  114,  114,  114,  114,  114,  114,   10,  114,  114,
      114,   25,  102,  114,   31,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  114,   99,  114,  114,  114,
      114,  114,   18,  114,   28,  114,  114,  114,  114,    0,
        0,    0,    0,    0,  119,  118,  114,  114,  114,    6,
      114,  114,  114,  114,  114,  114,  114,  114,    2,  103,
       46,  114,  114,  114,  114,  114,  114,  114,  114,  114,
       15,  114,  114,  114,  114,  114,  114,   53,  114,  114,
      114,  114,   97,   41,  114,   16,  114,  114,   24,  114,
      114,  108,    0,    0,  110,    0,  114,  114,   13,   19,
       34,   48,  114,  114,  114,  114,  114,  114,   17,   47,
       29,  114,  114,  114,  114,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  114,   42,   21,  114,  114,
      114,    8,  106,    0,    0,    0,  114,  114,  114,  114,
      114,  114,  114,   26,    3,  114,  114,  114,   55,  114,
      114,  114,  114,  114,   36,   33,  114,   12,    4,   54,
       27,   22,   52,  114,  114,    0,  111,    0,  114,   23,
      114,  114,  101,    7,  114,   20,   11,  114,  114,  114,
      114,  114,   37,   32,    0,   38,  114,  107,  109,   40,
      114,   14,   45,   98,  114,  114,  114,   39,    0,   56,
      114,  114,   35,  114,    0,  114,   44,  114,    0,   43,
      114,    5,  114,  114,   30,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,   27,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   43,
       29,   30,   31,   32,   33,   28,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   43,   59,   60,   61,   62,    1,   28,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    3,    3,
        3,    3,    3
    } ;

static yyconst short int yy_base[406] =
    {   0,
        0,    0,   61,   62,  455,  454,   63,   66,  453,  452,
       76,   80,  454,  459,  459,  450,  459,  427,  459,    0,
      426,  440,  459,  459,  459,  424,   65,  459,   67,  430,
       72,   80,   84,   45,  459,  422,  421,  420,   72,  459,
      459,  459,    0,   59,   55,   75,   83,   63,   88,  399,
       60,  401,   34,  387,   73,  403,   94,   93,  393,  104,
      398,  459,  378,  459,  459,  459,  459,  418,  459,  459,
      459,  459,  459,  459,  132,    0,  459,  459,  459,  459,
      433,  401,  396,  388,  390,  428,  459,    0,  459,  459,
      459,  459,  459,  459,  459,  412,  459,  459,  459,  120,

      133,  129,  137,  459,  459,  459,  459,  459,  404,  403,
        0,  375,    0,  378,  387,  107,  390,  376,  133,  376,
      367,  368,  119,  374,  371,  369,  365,  368,  366,    0,
      118,  378,  359,  355,  365,  371,  366,  372,  127,  367,
      360,  370,  352,  126,  144,  129,  350,  350,  349,  139,
      357,  459,  459,  459,  459,  459,  459,  459,  395,  136,
      358,  344,  348,    0,  459,  170,  176,  459,  459,  341,
      348,  358,  353,  354,  337,  140,  343,  353,  348,    0,
      350,  346,  380,  336,  329,  346,  345,  340,  341,  341,
      322,  336,    0,  331,    0,  327,  320,  315,  324,  334,

      313,  312,  327,  326,  312,  320,    0,  323,  313,  307,
      310,  319,    0,  322,    0,  302,  317,  319,  307,  313,
      314,  315,  310,  313,  459,  459,  295,  307,  300,    0,
      302,  290,  288,  298,  305,  284,  297,  291,  293,  459,
        0,  296,  288,  279,  297,  277,  295,  294,  276,  271,
        0,  274,  290,  281,  276,  279,  269,    0,  283,  280,
      270,  265,    0,    0,  259,    0,  275,  259,    0,  259,
      273,  459,  269,  255,  266,  262,  272,  271,    0,    0,
        0,  253,  256,  251,  256,  266,  261,  259,    0,  252,
        0,  260,  253,  249,  246,  253,  253,  248,  236,  252,

      249,  235,  238,  231,  246,  242,    0,  229,  242,  245,
      236,    0,  459,  232,  237,  230,  238,  226,  218,  217,
      232,  216,  215,    0,    0,  209,  225,  217,    0,  228,
      229,  229,  224,  222,    0,    0,  221,    0,  253,    0,
        0,    0,    0,  212,  211,  202,  459,  196,  200,    0,
      216,  213,    0,    0,  212,    0,    0,  202,  210,  211,
      197,  207,    0,    0,  208,    0,  204,  459,  459,    0,
      184,    0,    0,    0,  160,  168,  157,    0,  170,    0,
      155,  163,    0,  159,  148,  148,    0,  151,  156,    0,
      123,  459,  107,   92,    0,  459,  215,  219,  223,  227,

      231,   91,  234,  236,  239
    } ;

static yyconst short int yy_def[406] =
    {   0,
      396,    1,  397,  397,  398,  398,  399,  399,  400,  400,
      401,  401,  396,  396,  396,  396,  396,  396,  396,  402,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  404,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  405,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  405,  396,  396,  396,  396,  396,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  396,
      396,  396,  396,  396,  396,  396,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  396,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  396,  396,  396,  396,  396,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  396,  396,  396,  396,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  396,  396,  396,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  396,  403,  403,  396,  396,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  396,  403,
      403,  403,  403,  403,  396,  403,  403,  403,  396,  403,
      403,  396,  403,  403,  403,    0,  396,  396,  396,  396,

      396,  396,  396,  396,  396
    } ;

static yyconst short int yy_nxt[523] =
    {   0,
       14,   15,   16,   17,   15,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   14,   40,   14,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       43,   51,   43,   43,   52,   43,   53,   54,   55,   43,
       56,   57,   58,   59,   60,   61,   43,   43,   62,   63,
       64,   65,   14,   67,   67,   72,  104,  133,   72,   73,
      105,  134,   73,   74,   68,   68,   74,   80,   81,   92,
       80,   80,   81,   94,   80,   97,  109,  135,  110,   93,
       98,   95,   75,  112,   88,   75,   99,  100,  130,  101,

      101,  100,  114,  103,  103,  115,  131,  122,  116,  123,
      113,   82,   83,   84,   85,   82,   83,   84,   85,  117,
      119,  124,  118,  137,  120,   76,  138,  140,   76,  125,
      121,  141,  126,  145,  142,  127,  102,  148,  154,  166,
      166,  128,  395,  146,  394,  149,  143,  144,  167,  167,
      100,  150,  101,  101,  100,  183,  103,  103,  173,  174,
      207,  155,  167,  167,  167,  167,  167,  167,  177,  191,
      192,  178,  184,  200,  208,  393,  201,  179,  156,  202,
      217,  209,  212,  218,  157,  210,  213,  220,  221,  166,
      166,  233,  234,  392,  211,  167,  167,  391,  390,  389,

      388,  387,  386,  385,  384,  383,  225,  382,  226,  167,
      167,  167,  167,  167,  167,   66,   66,   66,   66,   69,
       69,   69,   69,   71,   71,   71,   71,   77,   77,   77,
       77,   79,   79,   79,   79,  111,  381,  111,  158,  158,
      164,  380,  164,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,

      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  232,  231,
      230,  229,  228,  227,  224,  223,  222,  159,  219,  216,

      215,  214,  206,  205,  204,  203,  199,  198,  197,  196,
      195,  194,  193,  190,  189,  188,  187,  186,  185,  182,
      181,  180,  176,  175,  172,  171,  170,  169,  168,  165,
       86,  163,  162,  161,  160,  159,  153,  152,  151,  147,
      139,  136,  132,  129,  108,  107,  106,   96,   91,   90,
       89,   87,   86,  396,   78,   78,   70,   70,   13,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396
    } ;

static yyconst short int yy_chk[523] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,   34,   53,    8,    7,
       34,   53,    8,    7,    3,    4,    8,   11,   11,   27,
       11,   12,   12,   29,   12,   31,   39,   53,   39,   27,
       31,   29,    7,   44,  402,    8,   31,   32,   51,   32,

       32,   33,   45,   33,   33,   45,   51,   48,   46,   48,
       44,   11,   11,   11,   11,   12,   12,   12,   12,   46,
       47,   49,   46,   55,   47,    7,   55,   57,    8,   49,
       47,   57,   49,   58,   57,   49,   32,   60,   75,  100,
      100,   49,  394,   58,  393,   60,   57,   57,  102,  102,
      101,   60,  101,  101,  103,  123,  103,  103,  116,  116,
      144,   75,  102,  102,  102,  102,  102,  102,  119,  131,
      131,  119,  123,  139,  144,  391,  139,  119,   75,  139,
      150,  145,  146,  150,   75,  145,  146,  160,  160,  166,
      166,  176,  176,  389,  145,  167,  167,  388,  386,  385,

      384,  382,  381,  379,  377,  376,  166,  375,  166,  167,
      167,  167,  167,  167,  167,  397,  397,  397,  397,  398,
      398,  398,  398,  399,  399,  399,  399,  400,  400,  400,
      400,  401,  401,  401,  401,  403,  371,  403,  404,  404,
      405,  367,  405,  365,  362,  361,  360,  359,  358,  355,
      352,  351,  349,  348,  346,  345,  344,  339,  337,  334,
      333,  332,  331,  330,  328,  327,  326,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  311,  310,  309,
      308,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  290,  288,  287,  286,

      285,  284,  283,  282,  278,  277,  276,  275,  274,  273,
      271,  270,  268,  267,  265,  262,  261,  260,  259,  257,
      256,  255,  254,  253,  252,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  229,  228,  227,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  214,  212,  211,  210,  209,
      208,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  194,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  179,  178,  177,  175,  174,
      173,  172,  171,  170,  163,  162,  161,  159,  151,  149,

      148,  147,  143,  142,  141,  140,  138,  137,  136,  135,
      134,  133,  132,  129,  128,  127,  126,  125,  124,  122,
      121,  120,  118,  117,  115,  114,  112,  110,  109,   96,
       86,   85,   84,   83,   82,   81,   68,   63,   61,   59,
       56,   54,   52,   50,   38,   37,   36,   30,   26,   22,
       21,   18,   16,   13,   10,    9,    6,    5,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "diksam.l"
#define INITIAL 0
#line 3 "diksam.l"
#undef YY_INPUT
#define YY_INPUT(buf, result, max_size) (result = my_yyinput(buf, max_size))
#include <stdio.h>
#include <string.h>
#include "DBG.h"
#include "diksamc.h"
#include "y.tab.h"

#ifdef __cplusplus
extern "C"
{
#endif

static int
file_input(char *buf, int max_size)
{
    int ch;
    int len;

    if (feof(yyin))
        return 0;

    for (len = 0; len < max_size; len++) {
        ch = getc(yyin);
        if (ch == EOF)
            break;
        buf[len] = ch;
    }
    return len;
}

static char **st_source_string;
static int st_current_source_line;
static int st_current_char_index;
static int isInSwitch=0;

void
dkc_set_source_string(char **source)
{
    st_source_string = source;
    st_current_source_line = 0;
    st_current_char_index = 0;
}

static int
string_input(char *buf, int max_size)
{
    int len;

    if (st_source_string[st_current_source_line] == NULL)
        return 0;

    while (st_source_string[st_current_source_line][st_current_char_index]
        == '\0') {
        st_current_source_line++;
        st_current_char_index = 0;
        if (st_source_string[st_current_source_line] == NULL)
            return 0;
    }

    if (st_source_string[st_current_source_line] == NULL)
        return 0;

    len = smaller(strlen(st_source_string[st_current_source_line])
                  - st_current_char_index,
                  max_size-1);//modified
	buf[max_size-1]=0;   //modified
    strncpy(buf,
            &st_source_string[st_current_source_line][st_current_char_index],
            len+1);//modified
    st_current_char_index += len;
	/*len=strlen("function print(str as string) as void end\n");
	strncpy(buf,"function print(str as string) as void end\n",len+1);*/
	//printf("STR INPUT:\n%s{END}",buf);
    return len;
}

static int
my_yyinput(char *buf, int max_size)
{
    int result;

    switch (dkc_get_current_compiler()->input_mode) {
    case FILE_INPUT_MODE:
        result = file_input(buf, max_size);
        break;
    case STRING_INPUT_MODE:
        result = string_input(buf, max_size);
        break;
    default:
        DBG_panic(("bad default. input_mode..%d\n",
                   dkc_get_current_compiler()->input_mode));
    }

    return result;
}


int
yywrap(void)
{
    return 1;
}

static void
increment_line_number(void)
{
    dkc_get_current_compiler()->current_line_number++;
}

static void
increment_line_number_int(int i)
{
    dkc_get_current_compiler()->current_line_number+=i;
}

DVM_Boolean st_character_literal_state;

#ifdef __cplusplus
}
#endif

#define C_COMMENT 1
#define CC_COMMENT 2
#define STRING_LITERAL_STATE 3
#define SHIFT_JIS_2ND_CHAR 4
#define CHK_END_BLOCK 5

#line 743 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 127 "diksam.l"

#line 896 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 397 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 459 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 128 "diksam.l"
return IF;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 129 "diksam.l"
return ELSE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 130 "diksam.l"
return ELSIF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 131 "diksam.l"
{isInSwitch=1; return SWITCH;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 132 "diksam.l"
{isInSwitch=1; return SWITCH;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 133 "diksam.l"
return CASE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 134 "diksam.l"
return DEFAULT_T;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 135 "diksam.l"
return WHILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 136 "diksam.l"
return DO_T;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 137 "diksam.l"
return FOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 138 "diksam.l"
return FOREACH;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 139 "diksam.l"
return RETURN_T;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 140 "diksam.l"
return BREAK;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 141 "diksam.l"
return CONTINUE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "diksam.l"
return NULL_T;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 143 "diksam.l"
return TRUE_T;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 144 "diksam.l"
return FALSE_T;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 145 "diksam.l"
return TRY;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 146 "diksam.l"
return CATCH;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 147 "diksam.l"
return FINALLY;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 148 "diksam.l"
return THROW;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 149 "diksam.l"
return THROWS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "diksam.l"
return BOOLEAN_T;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 151 "diksam.l"
return VOID_T;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 152 "diksam.l"
return INT_T;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 153 "diksam.l"
return DOUBLE_T;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 154 "diksam.l"
return STRING_T;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "diksam.l"
return VARIENT_T;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 156 "diksam.l"
return FLOAT_T;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 157 "diksam.l"
return NATIVE_POINTER_T;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 158 "diksam.l"
return NEW;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 159 "diksam.l"
return REQUIRE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 160 "diksam.l"
return RENAME;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 161 "diksam.l"
return CLASS_T;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 162 "diksam.l"
return INTERFACE_T;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 163 "diksam.l"
return PUBLIC_T;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 164 "diksam.l"
return PRIVATE_T;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 165 "diksam.l"
return VIRTUAL_T;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 166 "diksam.l"
return OVERRIDE_T;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 167 "diksam.l"
return ABSTRACT_T;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 168 "diksam.l"
return THIS_T;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 169 "diksam.l"
return SUPER_T;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "diksam.l"
return CONSTRUCTOR;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 171 "diksam.l"
return INSTANCEOF;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 172 "diksam.l"
return DELEGATE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 173 "diksam.l"
return ENUM;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 174 "diksam.l"
return FINAL;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 175 "diksam.l"
return CONST;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 176 "diksam.l"
return LP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 177 "diksam.l"
return RP;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "diksam.l"
return APOSTROPHE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 179 "diksam.l"
return UNSAFE;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 180 "diksam.l"
return SAFE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 181 "diksam.l"
return SHARED;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 182 "diksam.l"
return GLOBAL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 183 "diksam.l"
return VOLATILE;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 185 "diksam.l"
{return LC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 186 "diksam.l"
{return RC;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 187 "diksam.l"
{increment_line_number_int(yyleng);  BEGIN CHK_END_BLOCK;  return CR;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 188 "diksam.l"
return LB;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 189 "diksam.l"
return RB;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 190 "diksam.l"
return SEMICOLON;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 191 "diksam.l"
return COLON;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 192 "diksam.l"
return COMMA;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 193 "diksam.l"
return LOGICAL_AND;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 194 "diksam.l"
return LOGICAL_OR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 195 "diksam.l"
return ASSIGN_T;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 196 "diksam.l"
return EQ;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 197 "diksam.l"
return NE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 198 "diksam.l"
return GT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 199 "diksam.l"
return GE;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 200 "diksam.l"
return LT;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 201 "diksam.l"
return LE;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 202 "diksam.l"
return ADD;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 203 "diksam.l"
return SUB;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 204 "diksam.l"
return MUL;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 205 "diksam.l"
return DIV;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 206 "diksam.l"
return MOD;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 207 "diksam.l"
return BIT_AND;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 208 "diksam.l"
return BIT_OR;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 209 "diksam.l"
return BIT_XOR;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 210 "diksam.l"
return BIT_NOT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 211 "diksam.l"
return ADD_ASSIGN_T;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 212 "diksam.l"
return SUB_ASSIGN_T;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 213 "diksam.l"
return ATM_ADD_ASSIGN_T;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 214 "diksam.l"
return ATM_SUB_ASSIGN_T;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 215 "diksam.l"
return MUL_ASSIGN_T;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 216 "diksam.l"
return DIV_ASSIGN_T;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 217 "diksam.l"
return MOD_ASSIGN_T;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 218 "diksam.l"
return INCREMENT;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 219 "diksam.l"
return DECREMENT;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 220 "diksam.l"
return EXCLAMATION;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 221 "diksam.l"
return DOT;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 222 "diksam.l"
return DOWN_CAST_BEGIN;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 223 "diksam.l"
return DOWN_CAST_END;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 224 "diksam.l"
return AS;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 225 "diksam.l"
return THEN;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 226 "diksam.l"
return FUNCTION;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 227 "diksam.l"
return BSUB;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 228 "diksam.l"
return DIM;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 229 "diksam.l"
return DECLARE;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 230 "diksam.l"
return LIB;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 231 "diksam.l"
{increment_line_number(); BEGIN CHK_END_BLOCK; return END;}//
	YY_BREAK
case YY_STATE_EOF(CHK_END_BLOCK):
#line 234 "diksam.l"
BEGIN INITIAL;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 235 "diksam.l"
{increment_line_number_int(yyleng);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 236 "diksam.l"
;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 237 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 242 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 247 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
		if(isInSwitch){
			isInSwitch=0;
		}
		else{
			return END;
		}
		};
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 257 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 262 "diksam.l"
{
		//printf("ELSE BLOCK END %d\n",dkc_get_current_compiler()->current_line_number);
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 268 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 273 "diksam.l"
{
		//printf("PASS @%d %s\n", dkc_get_current_compiler()->current_line_number,yytext);
		yyless(0);
		BEGIN INITIAL;

		};
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 279 "diksam.l"
{
    yylval.identifier = dkc_create_identifier(yytext);
    return AUTOVAR;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 283 "diksam.l"
{
    yylval.identifier = dkc_create_identifier(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 287 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    sscanf(yytext, "%d", &expression->u.int_value);
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 293 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    sscanf(yytext, "%x", &expression->u.int_value);
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 299 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    expression->u.int_value = 0;
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 305 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(FLOAT_EXPRESSION);
    sscanf(yytext, "%lf", &expression->u.double_value);
    yylval.expression = expression;
    return FLOAT_LITERAL;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 311 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(DOUBLE_EXPRESSION);
    sscanf(yytext, "%lf", &expression->u.double_value);
    yylval.expression = expression;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 317 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(DOUBLE_EXPRESSION);
    sscanf(yytext, "%lf", &expression->u.double_value);
    yylval.expression = expression;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 323 "diksam.l"
{
    dkc_open_string_literal();
    st_character_literal_state = DVM_FALSE;
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 328 "diksam.l"
{
    dkc_open_string_literal();
    st_character_literal_state = DVM_TRUE;
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 333 "diksam.l"
;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 334 "diksam.l"
{increment_line_number_int(yyleng);BEGIN CHK_END_BLOCK;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 335 "diksam.l"
BEGIN C_COMMENT;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 336 "diksam.l"
BEGIN CC_COMMENT;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 337 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      CHARACTER_INVALID_ERR,
                      CHARACTER_MESSAGE_ARGUMENT, "bad_char", yytext[0],
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 343 "diksam.l"
{increment_line_number();}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 344 "diksam.l"
{
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 347 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      EOF_IN_C_COMMENT_ERR,
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 352 "diksam.l"
;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 353 "diksam.l"
{
    increment_line_number();
	BEGIN CHK_END_BLOCK;
    //BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(CC_COMMENT):
#line 358 "diksam.l"
BEGIN INITIAL;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 359 "diksam.l"
;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 360 "diksam.l"
{
    if (st_character_literal_state) {
        dkc_add_string_literal('\"');
    } else {
        Expression *expression = dkc_alloc_expression(STRING_EXPRESSION);
        expression->u.string_value = dkc_close_string_literal();
        yylval.expression = expression;
        BEGIN INITIAL;
        return STRING_LITERAL;
    }
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 371 "diksam.l"
{
    if (st_character_literal_state) {
        Expression *expression = dkc_alloc_expression(INT_EXPRESSION);
        expression->u.int_value = dkc_close_character_literal();
        yylval.expression = expression;
        BEGIN INITIAL;
        return INT_LITERAL;
    } else {
        dkc_add_string_literal('\'');
    }
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 382 "diksam.l"
{
    dkc_add_string_literal('\n');
    increment_line_number();
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 386 "diksam.l"
dkc_add_string_literal('"');
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 387 "diksam.l"
dkc_add_string_literal('\n');
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 388 "diksam.l"
dkc_add_string_literal('\t');
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 389 "diksam.l"
dkc_add_string_literal('\\');
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 390 "diksam.l"
{
  dkc_add_string_literal(yytext[0]);
  dkc_add_string_literal(yytext[1]);
}
	YY_BREAK
case YY_STATE_EOF(STRING_LITERAL_STATE):
#line 394 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      EOF_IN_STRING_LITERAL_ERR,
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 399 "diksam.l"
{
    Encoding enc = dkc_get_current_compiler()->source_encoding;
    dkc_add_string_literal(yytext[0]);
    if (enc == SHIFT_JIS_ENCODING
        && ((((unsigned char*)yytext)[0] >= 0x81
             && ((unsigned char*)yytext)[0] <= 0x9e)
            || (((unsigned char*)yytext)[0] >= 0xe0
                && ((unsigned char*)yytext)[0] <= 0xef))) {
        BEGIN SHIFT_JIS_2ND_CHAR;
    }
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 410 "diksam.l"
{
    dkc_add_string_literal(yytext[0]);
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 417 "diksam.l"
ECHO;
	YY_BREAK
#line 1847 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SHIFT_JIS_2ND_CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 397 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 397 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 396);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 417 "diksam.l"

