/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 133
#define YY_END_OF_BUFFER 134
static yyconst short int yy_accept[362] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  134,  117,  113,   53,  114,   84,  111,  117,
       72,   73,  112,   48,   49,   70,   68,   58,   69,   85,
       71,  109,  107,   57,   56,   66,   61,   64,   54,   55,
       75,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  117,   74,
      117,   76,  120,  118,  120,  122,  121,  131,  125,  123,
      124,  131,  131,  132,  133,  104,   97,   96,  104,  104,
      104,  104,   53,   63,  105,   81,   59,   79,   82,   77,
       83,   78,    0,  115,  116,   80,    0,    0,    0,  107,

       86,   87,   67,   62,   65,  106,  106,   88,  106,  106,
      106,  106,  106,  106,  106,    9,  106,  106,  106,  106,
      106,  106,    1,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,   51,   60,   52,  119,  126,  129,  127,  128,  130,
       96,    0,    0,    0,    0,  105,   50,  110,  108,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,   92,
      106,  106,  106,  106,  106,  106,   10,  106,  106,   25,
       94,  106,   30,  106,  106,  106,  106,  106,  106,  106,
      106,  106,   91,  106,  106,  106,  106,  106,   18,   28,

      106,  106,  106,    0,    0,    0,    0,    0,  106,  106,
      106,    6,  106,  106,  106,  106,  106,  106,  106,  106,
        2,   95,   45,  106,  106,  106,  106,  106,  106,  106,
       15,  106,  106,  106,  106,  106,  106,  106,  106,  106,
       89,   40,  106,   16,  106,   24,  106,  100,    0,    0,
      102,    0,  106,  106,   13,   19,   33,   47,  106,  106,
      106,  106,  106,  106,   17,   46,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,   41,
       21,  106,    8,   98,    0,    0,    0,  106,  106,  106,
      106,  106,  106,  106,   26,    3,  106,  106,  106,  106,

      106,  106,  106,  106,   35,   32,  106,   12,    4,   27,
       22,  106,    0,  103,    0,  106,   23,  106,  106,   93,
        7,  106,   20,   11,  106,  106,  106,  106,  106,   36,
       31,    0,   37,   99,  101,   39,  106,   14,   44,   90,
      106,  106,  106,   38,    0,  106,  106,   34,  106,    0,
      106,   43,  106,    0,   42,  106,    5,  106,  106,   29,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,   27,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   42,
       28,   29,   30,   31,   32,   27,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   42,   58,   59,   60,   61,    1,   27,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,    1,    1,    1
    } ;

static yyconst int yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    3,    3,    3,
        3,    3
    } ;

static yyconst short int yy_base[371] =
    {   0,
        0,    0,   60,   61,  422,  421,   62,   65,  420,  419,
       75,   79,  421,  426,  426,  417,  426,  394,  426,    0,
      393,  407,  426,  426,  426,  391,   64,  426,   68,  397,
       73,   79,   83,   44,  426,  389,  388,  387,  426,  426,
      426,    0,   37,   36,   62,   81,   61,   90,   83,  370,
       93,  356,   83,  372,   88,   92,  106,  368,  404,  347,
      402,  426,  426,  426,  385,  426,  426,  426,  426,  426,
      426,  127,    0,  426,  426,  426,  426,  400,  369,  364,
      356,  358,  395,  426,    0,  426,  426,  426,  426,  426,
      426,  426,  379,  426,  426,  426,   99,  130,  124,  134,

      426,  426,  426,  426,  426,    0,  345,    0,  348,  357,
      112,  360,  346,  130,  346,  337,  338,  113,  344,  341,
      336,  339,    0,  118,  350,  331,  327,  337,  343,  338,
      344,  126,  333,  326,  133,  139,  129,  325,  324,  332,
      331,  426,  426,  426,  426,  426,  426,  426,  426,  426,
      368,  132,  332,  318,  322,    0,  426,  167,  170,  315,
      322,  332,  327,  328,  311,  141,  317,  327,  322,    0,
      324,  320,  353,  310,  303,  320,  315,  316,  298,  312,
        0,  307,    0,  303,  296,  291,  300,  310,  289,  288,
      303,  298,    0,  301,  291,  285,  288,  297,    0,    0,

      281,  296,  287,  293,  294,  295,  290,  293,  275,  287,
      280,    0,  282,  270,  268,  278,  285,  264,  277,  271,
      273,  426,    0,  276,  268,  278,  258,  276,  258,  253,
        0,  256,  272,  263,  258,  261,  251,  265,  253,  248,
        0,    0,  242,    0,  243,    0,  258,  426,  254,  240,
      251,  247,  257,  256,    0,    0,    0,  238,  241,  236,
      241,  251,  246,  244,    0,  237,  245,  238,  232,  239,
      239,  234,  222,  238,  235,  221,  224,  217,  229,    0,
      216,  233,    0,  426,  221,  226,  219,  227,  215,  207,
      206,  221,  205,  204,    0,    0,  198,  214,  206,  217,

      218,  218,  213,  211,    0,    0,  210,    0,  241,    0,
        0,  201,  192,  426,  186,  190,    0,  206,  203,    0,
        0,  202,    0,    0,  192,  200,  200,  182,  165,    0,
        0,  166,    0,  426,  426,    0,  148,    0,    0,    0,
      152,  161,  150,    0,  163,  148,  156,    0,  144,  126,
      121,    0,   92,   71,    0,   50,  426,   59,   40,    0,
      426,  208,  212,  216,  220,  224,   63,  227,  229,  232
    } ;

static yyconst short int yy_def[371] =
    {   0,
      361,    1,  362,  362,  363,  363,  364,  364,  365,  365,
      366,  366,  361,  361,  361,  361,  361,  361,  361,  367,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  369,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  370,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,

      361,  361,  361,  361,  361,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  370,  361,  361,  361,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  361,  361,  361,  361,  361,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  361,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  361,  361,  361,
      361,  361,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  361,  361,  361,  361,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  361,  361,  361,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  361,  368,  361,  361,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  361,  368,  368,  368,  368,  361,
      368,  368,  368,  361,  368,  368,  361,  368,  368,  368,
        0,  361,  361,  361,  361,  361,  361,  361,  361,  361
    } ;

static yyconst short int yy_nxt[489] =
    {   0,
       14,   15,   16,   17,   15,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   14,   39,   14,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   42,   42,
       49,   42,   42,   50,   42,   51,   52,   53,   42,   54,
       55,   56,   42,   57,   58,   42,   42,   59,   60,   61,
       62,   14,   64,   64,   69,  101,   85,   69,   70,  102,
      107,   70,   71,   65,   65,   71,   77,   78,   89,   77,
       77,   78,  109,   77,   91,  110,   94,  108,   90,  360,
       72,   95,   92,   72,  111,  359,   97,   96,   98,   98,

       97,  358,  100,  100,  117,  112,  118,  357,  113,   79,
       80,   81,   82,   79,   80,   81,   82,  114,  158,  158,
      123,  115,  119,   73,  133,  126,   73,  116,  124,  127,
      120,  136,  130,  146,   99,  131,  121,  356,  138,  134,
      135,  137,  122,  159,  159,  128,  139,   97,  173,   98,
       98,   97,  140,  100,  100,  147,  159,  159,  159,  159,
      159,  159,  163,  164,  167,  174,  193,  168,  179,  180,
      355,  188,  148,  169,  189,  195,  354,  190,  149,  196,
      194,  198,  204,  205,  353,  199,  158,  158,  197,  159,
      159,  215,  216,  352,  351,  350,  349,  348,  347,  346,

      345,  344,  159,  159,  159,  159,  159,  159,   63,   63,
       63,   63,   66,   66,   66,   66,   68,   68,   68,   68,
       74,   74,   74,   74,   76,   76,   76,   76,  106,  343,
      106,  150,  150,  156,  342,  156,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,

      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      151,  203,  202,  201,  200,  192,  191,  187,  186,  185,
      184,  183,  182,  181,  178,  177,  176,  175,  172,  171,
      170,  166,  165,  162,  161,  160,  157,   83,  155,  154,

      153,  152,  151,  145,  144,  143,  142,  141,  132,  129,
      125,  105,  104,  103,   93,   88,   87,   86,   84,   83,
      361,   75,   75,   67,   67,   13,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361
    } ;

static yyconst short int yy_chk[489] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    7,   34,  367,    8,    7,   34,
       43,    8,    7,    3,    4,    8,   11,   11,   27,   11,
       12,   12,   44,   12,   29,   44,   31,   43,   27,  359,
        7,   31,   29,    8,   45,  358,   32,   31,   32,   32,

       33,  356,   33,   33,   47,   45,   47,  354,   45,   11,
       11,   11,   11,   12,   12,   12,   12,   46,   97,   97,
       49,   46,   48,    7,   55,   51,    8,   46,   49,   51,
       48,   56,   53,   72,   32,   53,   48,  353,   57,   55,
       55,   56,   48,   99,   99,   51,   57,   98,  118,   98,
       98,  100,   57,  100,  100,   72,   99,   99,   99,   99,
       99,   99,  111,  111,  114,  118,  135,  114,  124,  124,
      351,  132,   72,  114,  132,  136,  350,  132,   72,  136,
      135,  137,  152,  152,  349,  137,  158,  158,  136,  159,
      159,  166,  166,  347,  346,  345,  343,  342,  341,  337,

      332,  329,  159,  159,  159,  159,  159,  159,  362,  362,
      362,  362,  363,  363,  363,  363,  364,  364,  364,  364,
      365,  365,  365,  365,  366,  366,  366,  366,  368,  328,
      368,  369,  369,  370,  327,  370,  326,  325,  322,  319,
      318,  316,  315,  313,  312,  309,  307,  304,  303,  302,
      301,  300,  299,  298,  297,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  282,  281,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  264,  263,  262,  261,  260,  259,  258,  254,  253,
      252,  251,  250,  249,  247,  245,  243,  240,  239,  238,

      237,  236,  235,  234,  233,  232,  230,  229,  228,  227,
      226,  225,  224,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  198,  197,  196,  195,  194,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  182,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  169,  168,
      167,  165,  164,  163,  162,  161,  160,  155,  154,  153,
      151,  141,  140,  139,  138,  134,  133,  131,  130,  129,
      128,  127,  126,  125,  122,  121,  120,  119,  117,  116,
      115,  113,  112,  110,  109,  107,   93,   83,   82,   81,

       80,   79,   78,   65,   61,   60,   59,   58,   54,   52,
       50,   38,   37,   36,   30,   26,   22,   21,   18,   16,
       13,   10,    9,    6,    5,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "diksam.l"
#define INITIAL 0
#line 3 "diksam.l"
#undef YY_INPUT
#define YY_INPUT(buf, result, max_size) (result = my_yyinput(buf, max_size))
#include <stdio.h>
#include <string.h>
#include "..\include\DBG.h"
#include "diksamc.h"
#include "y.tab.h"

static int
file_input(char *buf, int max_size)
{
    int ch;
    int len;

    if (feof(yyin))
        return 0;

    for (len = 0; len < max_size; len++) {
        ch = getc(yyin);
        if (ch == EOF)
            break;
        buf[len] = ch;
    }
    return len;
}

static char **st_source_string;
static int st_current_source_line;
static int st_current_char_index;
static int isInSwitch=0;

void
dkc_set_source_string(char **source)
{
    st_source_string = source;
    st_current_source_line = 0;
    st_current_char_index = 0;
}

static int
string_input(char *buf, int max_size)
{
    int len;
	
    if (st_source_string[st_current_source_line] == NULL)
        return 0;

    while (st_source_string[st_current_source_line][st_current_char_index]
        == '\0') {
        st_current_source_line++;
        st_current_char_index = 0;
        if (st_source_string[st_current_source_line] == NULL)
            return 0;
    }

    if (st_source_string[st_current_source_line] == NULL)
        return 0;

    len = smaller(strlen(st_source_string[st_current_source_line])
                  - st_current_char_index,
                  max_size-1);//modified
	buf[max_size-1]=0;   //modified
    strncpy(buf,
            &st_source_string[st_current_source_line][st_current_char_index],
            len+1);//modified
    st_current_char_index += len;
	/*len=strlen("function print(str as string) as void end\n");
	strncpy(buf,"function print(str as string) as void end\n",len+1);*/
	//printf("STR INPUT:\n%s{END}",buf);
    return len;
}

static int
my_yyinput(char *buf, int max_size)
{
    int result;

    switch (dkc_get_current_compiler()->input_mode) {
    case FILE_INPUT_MODE:
        result = file_input(buf, max_size);
        break;
    case STRING_INPUT_MODE:
        result = string_input(buf, max_size);
        break;
    default:
        DBG_panic(("bad default. input_mode..%d\n",
                   dkc_get_current_compiler()->input_mode));
    }

    return result;
}


int
yywrap(void)
{
    return 1;
}

static void
increment_line_number(void)
{
    dkc_get_current_compiler()->current_line_number++;
}

static void
increment_line_number_int(int i)
{
    dkc_get_current_compiler()->current_line_number+=i;
}

DVM_Boolean st_character_literal_state;
#define C_COMMENT 1
#define CC_COMMENT 2
#define STRING_LITERAL_STATE 3
#define SHIFT_JIS_2ND_CHAR 4
#define CHK_END_BLOCK 5

#line 709 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 117 "diksam.l"

#line 862 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 362 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 426 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "diksam.l"
return IF;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "diksam.l"
return ELSE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 120 "diksam.l"
return ELSIF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 121 "diksam.l"
{isInSwitch=1; return SWITCH;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 122 "diksam.l"
{isInSwitch=1; return SWITCH;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "diksam.l"
return CASE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 124 "diksam.l"
return DEFAULT_T;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 125 "diksam.l"
return WHILE;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "diksam.l"
return DO_T;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 127 "diksam.l"
return FOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 128 "diksam.l"
return FOREACH;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 129 "diksam.l"
return RETURN_T;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 130 "diksam.l"
return BREAK;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 131 "diksam.l"
return CONTINUE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 132 "diksam.l"
return NULL_T;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 133 "diksam.l"
return TRUE_T;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 134 "diksam.l"
return FALSE_T;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 135 "diksam.l"
return TRY;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 136 "diksam.l"
return CATCH;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 137 "diksam.l"
return FINALLY;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 138 "diksam.l"
return THROW;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 139 "diksam.l"
return THROWS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 140 "diksam.l"
return BOOLEAN_T;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 141 "diksam.l"
return VOID_T;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 142 "diksam.l"
return INT_T;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 143 "diksam.l"
return DOUBLE_T;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 144 "diksam.l"
return STRING_T;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 145 "diksam.l"
return VARIENT_T;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 146 "diksam.l"
return NATIVE_POINTER_T;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "diksam.l"
return NEW;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "diksam.l"
return REQUIRE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 149 "diksam.l"
return RENAME;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 150 "diksam.l"
return CLASS_T;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "diksam.l"
return INTERFACE_T;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 152 "diksam.l"
return PUBLIC_T;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "diksam.l"
return PRIVATE_T;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "diksam.l"
return VIRTUAL_T;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "diksam.l"
return OVERRIDE_T;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 156 "diksam.l"
return ABSTRACT_T;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 157 "diksam.l"
return THIS_T;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "diksam.l"
return SUPER_T;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 159 "diksam.l"
return CONSTRUCTOR;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "diksam.l"
return INSTANCEOF;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 161 "diksam.l"
return DELEGATE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 162 "diksam.l"
return ENUM;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 163 "diksam.l"
return FINAL;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 164 "diksam.l"
return CONST;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 165 "diksam.l"
return LP;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 166 "diksam.l"
return RP;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 167 "diksam.l"
return APOSTROPHE;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 169 "diksam.l"
{increment_line_number();  return LC;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 170 "diksam.l"
{increment_line_number();  return RC;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 171 "diksam.l"
{increment_line_number_int(yyleng);  BEGIN CHK_END_BLOCK;  return CR;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 172 "diksam.l"
return LB;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 173 "diksam.l"
return RB;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 174 "diksam.l"
return SEMICOLON;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 175 "diksam.l"
return COLON;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 176 "diksam.l"
return COMMA;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 177 "diksam.l"
return LOGICAL_AND;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 178 "diksam.l"
return LOGICAL_OR;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 179 "diksam.l"
return ASSIGN_T;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 180 "diksam.l"
return EQ;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 181 "diksam.l"
return NE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 182 "diksam.l"
return GT;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 183 "diksam.l"
return GE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 184 "diksam.l"
return LT;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 185 "diksam.l"
return LE;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "diksam.l"
return ADD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "diksam.l"
return SUB;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "diksam.l"
return MUL;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 189 "diksam.l"
return DIV;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 190 "diksam.l"
return MOD;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 191 "diksam.l"
return BIT_AND;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 192 "diksam.l"
return BIT_OR;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 193 "diksam.l"
return BIT_XOR;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 194 "diksam.l"
return BIT_NOT;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 195 "diksam.l"
return ADD_ASSIGN_T;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 196 "diksam.l"
return SUB_ASSIGN_T;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 197 "diksam.l"
return MUL_ASSIGN_T;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 198 "diksam.l"
return DIV_ASSIGN_T;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 199 "diksam.l"
return MOD_ASSIGN_T;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 200 "diksam.l"
return INCREMENT;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 201 "diksam.l"
return DECREMENT;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 202 "diksam.l"
return EXCLAMATION;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 203 "diksam.l"
return DOT;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 204 "diksam.l"
return DOWN_CAST_BEGIN;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 205 "diksam.l"
return DOWN_CAST_END;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 206 "diksam.l"
return AS;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 207 "diksam.l"
return THEN;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 208 "diksam.l"
return FUNCTION;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 209 "diksam.l"
return BSUB;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 210 "diksam.l"
return DIM;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 211 "diksam.l"
return DECLARE;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 212 "diksam.l"
return LIB;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 213 "diksam.l"
{increment_line_number(); BEGIN CHK_END_BLOCK; return END;}// 
	YY_BREAK
case YY_STATE_EOF(CHK_END_BLOCK):
#line 216 "diksam.l"
BEGIN INITIAL;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 217 "diksam.l"
{increment_line_number_int(yyleng);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 218 "diksam.l"
;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 219 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 224 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 229 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
		if(isInSwitch){
			isInSwitch=0;
		}
		else{
			return END;
		}
		};
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 239 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 244 "diksam.l"
{
		//printf("ELSE BLOCK END %d\n",dkc_get_current_compiler()->current_line_number);
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 250 "diksam.l"
{
		yyless(0);
		BEGIN INITIAL;
        return END;
		};
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 255 "diksam.l"
{
		//printf("PASS @%d %s\n", dkc_get_current_compiler()->current_line_number,yytext);
		yyless(0);
		BEGIN INITIAL;
        
		};
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 261 "diksam.l"
{
    yylval.identifier = dkc_create_identifier(yytext);
    return AUTOVAR;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 265 "diksam.l"
{
    yylval.identifier = dkc_create_identifier(yytext);
    return IDENTIFIER;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 269 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    sscanf(yytext, "%d", &expression->u.int_value);
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 275 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    sscanf(yytext, "%x", &expression->u.int_value);
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 281 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(INT_EXPRESSION);
    expression->u.int_value = 0;
    yylval.expression = expression;
    return INT_LITERAL;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 287 "diksam.l"
{
    Expression  *expression = dkc_alloc_expression(DOUBLE_EXPRESSION);
    sscanf(yytext, "%lf", &expression->u.double_value);
    yylval.expression = expression;
    return DOUBLE_LITERAL;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 293 "diksam.l"
{
    dkc_open_string_literal();
    st_character_literal_state = DVM_FALSE;
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 298 "diksam.l"
{
    dkc_open_string_literal();
    st_character_literal_state = DVM_TRUE;
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 303 "diksam.l"
;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 304 "diksam.l"
{increment_line_number_int(yyleng);BEGIN CHK_END_BLOCK;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 305 "diksam.l"
BEGIN C_COMMENT;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 306 "diksam.l"
BEGIN CC_COMMENT;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 307 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      CHARACTER_INVALID_ERR,
                      CHARACTER_MESSAGE_ARGUMENT, "bad_char", yytext[0],
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 313 "diksam.l"
{increment_line_number();}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 314 "diksam.l"
{
    BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(C_COMMENT):
#line 317 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      EOF_IN_C_COMMENT_ERR,
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 322 "diksam.l"
;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 323 "diksam.l"
{
    increment_line_number();
	BEGIN CHK_END_BLOCK;
    //BEGIN INITIAL;
}
	YY_BREAK
case YY_STATE_EOF(CC_COMMENT):
#line 328 "diksam.l"
BEGIN INITIAL;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 329 "diksam.l"
;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 330 "diksam.l"
{
    if (st_character_literal_state) {
        dkc_add_string_literal('\"');
    } else {
        Expression *expression = dkc_alloc_expression(STRING_EXPRESSION);
        expression->u.string_value = dkc_close_string_literal();
        yylval.expression = expression;
        BEGIN INITIAL;
        return STRING_LITERAL;
    }
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 341 "diksam.l"
{
    if (st_character_literal_state) {
        Expression *expression = dkc_alloc_expression(INT_EXPRESSION);
        expression->u.int_value = dkc_close_character_literal();
        yylval.expression = expression;
        BEGIN INITIAL;
        return INT_LITERAL;
    } else {
        dkc_add_string_literal('\'');
    }
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 352 "diksam.l"
{
    dkc_add_string_literal('\n');
    increment_line_number();
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 356 "diksam.l"
dkc_add_string_literal('"');
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 357 "diksam.l"
dkc_add_string_literal('\n');
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 358 "diksam.l"
dkc_add_string_literal('\t');
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 359 "diksam.l"
dkc_add_string_literal('\\');
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 360 "diksam.l"
{
  dkc_add_string_literal(yytext[0]);
  dkc_add_string_literal(yytext[1]);
}
	YY_BREAK
case YY_STATE_EOF(STRING_LITERAL_STATE):
#line 364 "diksam.l"
{
    dkc_compile_error(dkc_get_current_compiler()->current_line_number,
                      EOF_IN_STRING_LITERAL_ERR,
                      MESSAGE_ARGUMENT_END);
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 369 "diksam.l"
{
    Encoding enc = dkc_get_current_compiler()->source_encoding;
    dkc_add_string_literal(yytext[0]);
    if (enc == SHIFT_JIS_ENCODING
        && ((((unsigned char*)yytext)[0] >= 0x81
             && ((unsigned char*)yytext)[0] <= 0x9e)
            || (((unsigned char*)yytext)[0] >= 0xe0
                && ((unsigned char*)yytext)[0] <= 0xef))) {
        BEGIN SHIFT_JIS_2ND_CHAR;
    }
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 380 "diksam.l"
{
    dkc_add_string_literal(yytext[0]);
    BEGIN STRING_LITERAL_STATE;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 384 "diksam.l"
ECHO;
	YY_BREAK
#line 1753 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SHIFT_JIS_2ND_CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 362 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 362 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 361);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 384 "diksam.l"

